### ISSUE TITLE
Minor python issues

### ISSUE THREAD

**Issue by memsharded** [Celtoys/PiB#1]
I see a few non-pythonic expressions, non pep8 format, usage of old style classes. Most are not a problem, but a couple of them can cause subtle bugs, like passing a mutable object as default parameter to functions.

The syntax is CamelCase, which is non pep8, but I wouldn't change it.

Would you like a PR addressing some of these issues?

**Comment by dwilliamson** [comment]
Thanks for taking time to review the code.

Right now this is the Python dialect I understand (even though I run Python 3, I'm still a die-hard Python 2 writer). I'm not accepting any PRs on code-style (camel case) or pep8 as this project is public as a learning experience for others - it's not intended for wider adoption.

However! Please open individual issues or PRs for stuff that you feel could cause bugs (like the mutable default parameter). I'd really like to shut down anything like that.
